# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    uploader.sondage_image: '%kernel.project_dir%/public/uploads/sondages'
    uploader.choix_image: '%kernel.project_dir%/public/uploads/choix'
    namer: vich_uploader.namer_uniqid  # Optionnel : dépend de l'implémentation de VichUploaderBundle

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
# config/packages/security.yaml
security:
    # Encoders for the User entities
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    # Where Symfony looks for authenticated users
    firewalls:
        # This is the part that handles the login process
        main:
            pattern: ^/
            form_login:
                login_path: app_utilisateur_login
                check_path: app_utilisateur_login
                default_target_path: app_sondage_list  # Page à rediriger après la connexion réussie
                username_parameter: _username
                password_parameter: _password
            logout:
                path: app_utilisateur_logout
                # Optionally, you can specify a redirection after logout
                target: app_utilisateur_login


    # User provider settings
    providers:
        database:
            entity:
                class: App\Entity\Utilisateur
                property: email
